### ISSUE TITLE
TBC Gear

### ISSUE THREAD

**Issue by mariakovaleva** [Cheesehyvel/magesim-wotlk#11]
Hi, I'm trying to sim pre-raid bis gear for phase 1. I'm trying to assess how good some of the TBC gear is at that stage of the game (mainly Tirisfal Regalia and Tempest Regalia), however when I try to add those as custom items there's no way to add the set bonuses. It also seems like there's no way to add the socket bonuses. 

When I add an item using an ID from wowhead, I can see in the tooltip that the item is pulled from the DB correctly, however, it doesn't seem like that data is actually used, so only the values you enter manually are accounted for.

Is there a way to add those items to the sim or add the possibility of entering custom set and socket bonuses?

Thank you!

**Comment by Cheesehyvel** [comment]
9eb387a
Added the t5 set and I believe the t6 set was already in there.

I don't plan on adding custom socket bonuses, this can be accomplished manually by adding bonus stats or simply adding the socket bonuses into the item itself.
The tooltip is just a script from wowhead that renders it automatically. The sim is not pulling any data.

I'm not gonna add custom set bonuses either. It should be very rare and most set bonuses require custom code.
