### ISSUE TITLE
Missing item: Incanter's Cowl

### ISSUE THREAD

**Issue by Vektyr** [Cheesehyvel/magesim-wotlk#12]
https://www.wowhead.com/wotlk/item=28278/incanters-cowl

Phase 1 Item

**Comment by Vektyr** [comment]
Tried to import the build below, but the item database could not find many of the items. Importing with an item ID would be awesome as it was pretty painful to enter each missing item by hand stat-by-stat. Excellent tool overall though I do appreciate it and look forward to supporting the cause in the near future!

`{
    "name": "T",
    "phase": 5,
    "links": {
        "talents": "https://eightyupgrades.com/talents/mage/1CFDGKIJNOPRUTSWZYx7AB2CbbF?g=0iw"
    },
    "character": {
        "name": "Test",
        "level": 70,
        "gameClass": "MAGE",
        "race": "TROLL",
        "faction": "HORDE"
    },
    "items": [
        {
            "name": "Incanter's Cowl",
            "id": 28278,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Tireless Starflare Diamond",
                    "id": 44078
                }
            ],
            "slot": "HEAD"
        },
        {
            "name": "Brooch of Heightened Potential",
            "id": 28134,
            "slot": "NECK"
        },
        {
            "name": "Duskhallow Mantle",
            "id": 34788,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "SHOULDERS"
        },
        {
            "name": "Warp Infused Drape",
            "id": 28342,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "CHEST"
        },
        {
            "name": "Cord of Reconstruction",
            "id": 34793,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "WAIST"
        },
        {
            "name": "Khadgar's Kilt of Abjuration",
            "id": 28185,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "LEGS"
        },
        {
            "name": "Sigil-Laced Boots",
            "id": 28406,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "FEET"
        },
        {
            "name": "Bindings of Raging Fire",
            "id": 34697,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "WRISTS"
        },
        {
            "name": "Gloves of Arcane Acuity",
            "id": 34808,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                },
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "HANDS"
        },
        {
            "name": "Kharmaa's Ring of Fate",
            "id": 34625,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "FINGER_1"
        },
        {
            "name": "Band of Frigid Elements",
            "id": 32779,
            "slot": "FINGER_2"
        },
        {
            "name": "Direbrew Hops",
            "id": 38288,
            "slot": "TRINKET_1"
        },
        {
            "name": "Dark Iron Smoking Pipe",
            "id": 38290,
            "slot": "TRINKET_2"
        },
        {
            "name": "Cloak of the Betrayed",
            "id": 34792,
            "gems": [
                {
                    "name": "Iridescent Fire Opal",
                    "id": 30593
                }
            ],
            "slot": "BACK"
        },
        {
            "name": "Keleseth's Blade of Evocation",
            "id": 35570,
            "slot": "MAIN_HAND"
        },
        {
            "name": "Lamp of Peaceful Radiance",
            "id": 28412,
            "slot": "OFF_HAND"
        },
        {
            "name": "Nether Core's Control Rod",
            "id": 28386,
            "slot": "RANGED"
        }
    ],
    "consumables": [],
    "buffs": [],
    "talents": [
        {
            "name": "Burning Soul",
            "id": 23,
            "rank": 2,
            "spellId": 12351
        },
        {
            "name": "Improved Scorch",
            "id": 25,
            "rank": 3,
            "spellId": 12873
        },
        {
            "name": "Improved Fireball",
            "id": 26,
            "rank": 5,
            "spellId": 12341
        },
        {
            "name": "Flame Throwing",
            "id": 28,
            "rank": 2,
            "spellId": 12353
        },
        {
            "name": "Pyroblast",
            "id": 29,
            "rank": 1,
            "spellId": 11366
        },
        {
            "name": "World in Flames",
            "id": 31,
            "rank": 3,
            "spellId": 12350
        },
        {
            "name": "Blast Wave",
            "id": 32,
            "rank": 1,
            "spellId": 11113
        },
        {
            "name": "Critical Mass",
            "id": 33,
            "rank": 3,
            "spellId": 11368
        },
        {
            "name": "Ignite",
            "id": 34,
            "rank": 5,
            "spellId": 12848
        },
        {
            "name": "Fire Power",
            "id": 35,
            "rank": 5,
            "spellId": 12400
        },
        {
            "name": "Combustion",
            "id": 36,
            "rank": 1,
            "spellId": 11129
        },
        {
            "name": "Improved Frostbolt",
            "id": 37,
            "rank": 2,
            "spellId": 12473
        },
        {
            "name": "Ice Floes",
            "id": 62,
            "rank": 3,
            "spellId": 55094
        },
        {
            "name": "Precision",
            "id": 1649,
            "rank": 3,
            "spellId": 29440
        },
        {
            "name": "Playing with Fire",
            "id": 1730,
            "rank": 3,
            "spellId": 31640
        },
        {
            "name": "Molten Fury",
            "id": 1732,
            "rank": 2,
            "spellId": 31680
        },
        {
            "name": "Pyromaniac",
            "id": 1733,
            "rank": 3,
            "spellId": 34296
        },
        {
            "name": "Empowered Fire",
            "id": 1734,
            "rank": 3,
            "spellId": 31658
        },
        {
            "name": "Dragon's Breath",
            "id": 1735,
            "rank": 1,
            "spellId": 31661
        },
        {
            "name": "Firestarter",
            "id": 1849,
            "rank": 1,
            "spellId": 44442
        },
        {
            "name": "Hot Streak",
            "id": 1850,
            "rank": 3,
            "spellId": 44448
        },
        {
            "name": "Burnout",
            "id": 1851,
            "rank": 5,
            "spellId": 44472
        },
        {
            "name": "Living Bomb",
            "id": 1852,
            "rank": 1,
            "spellId": 44457
        }
    ],
    "glyphs": [
        {
            "name": "Glyph of Evocation",
            "id": 42738,
            "type": "MAJOR"
        },
        {
            "name": "Glyph of Mana Gem",
            "id": 42750,
            "type": "MAJOR"
        }
    ],
    "points": [
        {
            "name": "Fire",
            "stats": {
                "spellDamage": 1,
                "fireDamage": 1,
                "critRating": 0.75,
                "hasteRating": 0.917,
                "hitRating": 1.25,
                "intellect": 0.417,
                "mp5": 0.417,
                "spirit": 0.167,
                "metaSockets": 30,
                "redSockets": 19,
                "yellowSockets": 19,
                "blueSockets": 19,
                "prismaticSockets": 19
            }
        }
    ],
    "stats": {
        "agility": 41,
        "arcaneDamage": 816,
        "armor": 1072,
        "attackPower": 58,
        "crit": 13.64,
        "critRating": 188,
        "defense": 350,
        "dodge": 5.11,
        "fireDamage": 816,
        "frostDamage": 816,
        "haste": 2.03,
        "hasteRating": 32,
        "healing": 816,
        "health": 5793,
        "hit": 4.57,
        "hitRating": 72,
        "holyDamage": 816,
        "intellect": 402,
        "mainHandSpeed": 1.8,
        "mana": 7991,
        "natureDamage": 816,
        "parry": 5,
        "shadowDamage": 816,
        "spellCrit": 17.45,
        "spellDamage": 816,
        "spellHaste": 2.03,
        "spellHit": 8.71,
        "spirit": 231,
        "stamina": 258,
        "strength": 34
    },
    "exportOptions": {
        "buffs": true,
        "talents": true
    }
}`

**Comment by Cheesehyvel** [comment]
Not gonna add tbc prebis items in the wotlk sim
