### ISSUE TITLE
'AB spam' is not computed properly

### ISSUE THREAD

**Issue by RFerat** [Cheesehyvel/magesim-wotlk#22]
Hi, and first of all thanks a lot for the work you put into this.

I found several issues in the computation of the 'AB spam' part of the Arcane rotation (_canBlast_) which i wanted to share :
- When using POM, it breaks the AB spam ; this is due to the casttime being 0 which breaks the logic (infinite loop). This is especially prevalent on 180s sim since pom is used on CD (3rd use around 170s)
- Mana cost computations seems wrong : baseManacost is used instead of manaCost so multipliers are ignored (0.94 generally for arcane) & deducted manacost should be base_cost * (1+1.75 * stacks) instead of base_cost * 1.75 * stacks
- Mana regen is not taken into account (small optimization)

Overall, the issues with mana tends to balance themselves out somewhat (maybe <5% cost difference in the end) so less important than the pom thing i feel.

Thanks

**Comment by Cheesehyvel** [comment]
ad046af

Fixed the endless loop.
Didn't touch the mana calculations. They don't need to be perfect and it's better that the function is fast and 95% accurate then slower and 100% accurate.
