### ISSUE TITLE
"Find average fight" doesn't work

### ISSUE THREAD

**Issue by jdelvare** [Cheesehyvel/magesim-wotlk#23]
**Describe the bug**
Clicking the "Find average fight" button spins forever without actually finding anything.

**Expected behavior**
I would expect the "Find average fight" button to find and display an average fight.

**Browser**
Bug reproduced with both Chromium 108.0.5359.124 (openSUSE Build) stable (64 bits) and Firefox 102.6.0esr (64 bits) on openSUSE Leap 15.3.

**Profile**
Bug reproduced with the default "Phase 1 Arcane Alliance" quick profile as well as my own gear+config, so I don't think the profile is relevant for this bug.

**Comment by Cheesehyvel** [comment]
This can happen if you click "Find average fight" after changing profile.
Can you reproduce this by clicking the button after finishing a run without changing anything? If so, can you open the web console (F12) and see if there are any error messages?

**Comment by jdelvare** [comment]
Thanks for the quick reply. I did not change the profile, clicked straight on "Find average fight" after a 3000-iteration run. This is not a new issue for me by the way, I noticed it several weeks ago, just never bothered reporting until today.

No error message in the Console tab. The Network tab shows a never-ending loop between 3 URL:
![average-fight-loop](https://user-images.githubusercontent.com/4045314/211600545-c8459207-f676-46f2-9b2d-d8d7671b565d.png)

**Comment by jdelvare** [comment]
OK, I made some progress. I cleared the cached data of my browser, and the bug went away. So I concluded that my personal settings are triggering the bug. After some trial and error, I figured out that this is caused by setting a fixed RNG seed. With the default setting (0), the bug does not happen. If I set it to my favorite number: **42** then the bug happens.
Hopefully you will be able to reproduce the bug by setting your RNG seed to 42.

**Comment by Cheesehyvel** [comment]
Yeah find avg doesn't quite make sense with a fixed rng seed. I'm just gonna disable that button when that is set.

**Comment by jdelvare** [comment]
Hmm, why is that? As I understand it, the RNG seed is only set for the first run of the series, you still get a different fight with every iteration, with a DPS which could be very different, as shown by the HISTOGRAM tab. So I would expect "Find average fight" to be still useful even with a fixed RNG seed.

On the other hand, I don't know what logic is used to determine what an average fight would be. I naively expected it to be the fight with the DPS as close as possible to the average DPS. Is it checking more than this?
