### ISSUE TITLE
Critical stats for Fireblast and Pyroblast

### ISSUE THREAD

**Issue by QuentinNIO** [Cheesehyvel/magesim-wotlk#29]
**Describe the bug**
I was trying to add a new rotation based on FrostFire, by adding fireblast when last spell was critical. What i got is ffb is always having +10% crits than any others spell (pyroblast, fireblast for example). I already tested locally by removing buff one by one, same result, crit modifier seam to work fine.   

**Expected behavior**
Without T9 4P bonus on frost-fire, i was expecting to have ~ same amount of crit between pyroblast, fireBlast and ffb (due to incineration and world_in_flame talent)

**Browser**
Brave (chrome)

**Profile**
Tested with default P3 bis profile

**Comment by QuentinNIO** [comment]
please let me know if i missed something that create such a difference.

**Comment by Cheesehyvel** [comment]
So this is a bug in a local change you made?
Not gonna debug this for you mate.

**Comment by QuentinNIO** [comment]
nop, i saw this locally and AFTER that i checked and reproduced it on mage-sim website using default configs

but consederring this really "welcome" message for this glhf.
