### ISSUE TITLE
Missing item: Cloth Helms

### ISSUE THREAD

**Issue by yurpcraft** [Cheesehyvel/magesim-wotlk#3]
Please include the item name in the title and a link to the item on any wotlk database (like wotlkdb.com or wowhead).

  Titan-Forged Hood of Dominance https://www.wowhead.com/wotlk/item=44910/titan-forged-hood-of-dominance
  Tattered Glacial-Woven Hood https://www.wowhead.com/wotlk/item=49849/tattered-glacial-woven-hood
  Gaze of the Unknown https://www.wowhead.com/wotlk/item=47564/gaze-of-the-unknown
  Khadgar's sets (the same as Sunstriders though so /shrug)
  Hood/Helm of Clouded Sight (Horde/Ally) https://www.wowhead.com/wotlk/item=47694/helm-of-clouded-sight
  Hood of Smouldering/Fiery Aftermath (Horde/Ally) https://www.wowhead.com/wotlk/item=47693/hood-of-fiery-aftermath

**Comment by Cheesehyvel** [comment]
8aa7ec1
