### ISSUE TITLE
Unit of stat weights in "DPS mode"

### ISSUE THREAD

**Issue by jdelvare** [Cheesehyvel/magesim-wotlk#32]
**Describe the bug**
The Stat weights feature gives the user a choice of how to display the weights. While the EP options are pretty clear (normalize all weights based on a given stat), the "DPS" option is confusing me.

**Expected behavior**
My expectation of the "DPS" option when displaying the stat weights is that the value displayed for each stat is how much DPS you gain on average by adding 1 of this stat.

However, experiments show that this isn't the case. For example, Spell power is displayed as having a weight of 3.93 in DPS mode for me. My expectation is therefore that adding a bonus of 100 Spell power would increase the simulated DPS by roughly 393. However, if I try that, the DPS increase is only 197.

(I chose Spell power because changes of this stat should be unaffected by RNG factors, thus simple tests like this should work just fine.)

So, if the displayed stat values aren't in "DPS unit", in which unit are they expressed?

Note that 197 is suspiciously close to 393/2, so I'm wondering if maybe there's simply a division by 2 missing in the computations.

**Browser**
Chromium version 118.0.5993.70 (openSUSE Build) stable (64 bits)

**Profile**
eyJlcXVpcHBlZCI6eyJ3ZWFwb24iOjQ3OTYwLCJvZmZfaGFuZCI6bnVsbCwicmFuZ2VkIjo0NTI5NCwiaGVhZCI6NDc3NTQsIm5lY2siOjUwODA5LCJzaG91bGRlciI6NDc3NTcsImJhY2siOjQ4NjcxLCJjaGVzdCI6NDc2MDMsIndyaXN0Ijo0NzU4NSwiaGFuZHMiOjQ3NzUzLCJ3YWlzdCI6NDU1NTcsImxlZ3MiOjQ3NzU1LCJmZWV0Ijo0NTU2NiwiZmluZ2VyMSI6NDU0OTUsImZpbmdlcjIiOjUwMzc3LCJ0cmlua2V0MSI6NDU1MTgsInRyaW5rZXQyIjo0NzE4Mn0sImVuY2hhbnRzIjp7IndlYXBvbiI6NjI5NDgsIm9mZl9oYW5kIjpudWxsLCJyYW5nZWQiOm51bGwsImhlYWQiOjU5OTcwLCJuZWNrIjpudWxsLCJzaG91bGRlciI6NTk5MzcsImJhY2siOjU1NjQyLCJjaGVzdCI6NjA2OTIsIndyaXN0Ijo2MDc2NywiaGFuZHMiOjU0OTk5LCJ3YWlzdCI6bnVsbCwibGVncyI6NTU2MzEsImZlZXQiOjU1MDE2LCJmaW5nZXIxIjpudWxsLCJmaW5nZXIyIjpudWxsLCJ0cmlua2V0MSI6bnVsbCwidHJpbmtldDIiOm51bGx9LCJnZW1zIjp7IndlYXBvbiI6WzQwMTMzLDQwMTU1LDQwMTU1XSwib2ZmX2hhbmQiOltudWxsLG51bGwsbnVsbF0sInJhbmdlZCI6WzQwMTU1LG51bGwsbnVsbF0sImhlYWQiOls0MTI4NSw0MDEzMyxudWxsXSwibmVjayI6WzQwMTUzLG51bGwsbnVsbF0sInNob3VsZGVyIjpbNDAxMzMsbnVsbCxudWxsXSwiYmFjayI6WzQwMTEzLG51bGwsbnVsbF0sImNoZXN0IjpbNDAxMzMsNDAxNTIsNDAxMTNdLCJ3cmlzdCI6WzQwMTMzLG51bGwsbnVsbF0sImhhbmRzIjpbNDAxMTMsbnVsbCxudWxsXSwid2Fpc3QiOls0MDEzMyw0MDExMyw0MDExM10sImxlZ3MiOls0MDE1NSw0MDE1NSxudWxsXSwiZmVldCI6WzQwMTMzLDQ1ODgzLG51bGxdLCJmaW5nZXIxIjpbNDAxMzMsbnVsbCxudWxsXSwiZmluZ2VyMiI6W251bGwsbnVsbCxudWxsXSwidHJpbmtldDEiOltudWxsLG51bGwsbnVsbF0sInRyaW5rZXQyIjpbbnVsbCxudWxsLG51bGxdfSwiY29uZmlnIjp7Iml0ZXJhdGlvbnMiOjEwMDAwMCwicmFjZSI6Miwic2hhdHRfZmFjdGlvbiI6MCwiZHVyYXRpb24iOjE4MCwiZHVyYXRpb25fdmFyaWFuY2UiOjMwLCJybmdfc2VlZCI6NDIsInN0YXRfd2VpZ2h0X2luY3JlbWVudCI6MjAsIm9ubHlfbWFpbl9kbWciOmZhbHNlLCJhdmdfc3BlbGxfZG1nIjp0cnVlLCJhZGRpdGlvbmFsX2RhdGEiOmZhbHNlLCJ0YXJnZXRzIjoxLCJkb3RfdGFyZ2V0cyI6MCwidGFyZ2V0X3Jlc2lzdGFuY2UiOjAsInRhcmdldF9sZXZlbCI6ODMsInRhcmdldF9ocCI6MTAwLCJkaXN0YW5jZSI6MzAsInJlYWN0aW9uX3RpbWUiOjMwMCwiZW5jb3VudGVycyI6ZmFsc2UsImRlYnVmZl9jcml0Ijp0cnVlLCJkZWJ1ZmZfc3BlbGxfY3JpdCI6dHJ1ZSwiZGVidWZmX3NwZWxsX2hpdCI6dHJ1ZSwiZGVidWZmX3NwZWxsX2RtZyI6dHJ1ZSwianVkZ2VtZW50X29mX3dpc2RvbSI6dHJ1ZSwiZ2lmdF9vZl9hcnRoYXMiOmZhbHNlLCJtYWdlX2FybW9yIjpmYWxzZSwibW9sdGVuX2FybW9yIjp0cnVlLCJhbXBsaWZ5X21hZ2ljIjp0cnVlLCJkaXZpbmVfc3Bpcml0Ijp0cnVlLCJmZWxfaW50ZWxsaWdlbmNlIjpmYWxzZSwibWFya19vZl90aGVfd2lsZCI6dHJ1ZSwiaW1wX21hcmtfb2ZfdGhlX3dpbGQiOnRydWUsInRvdGVtX29mX3dyYXRoIjpmYWxzZSwiZmxhbWV0b25ndWUiOnRydWUsImRlbW9uaWNfcGFjdCI6ZmFsc2UsImRlbW9uaWNfcGFjdF9ib251cyI6MzUwLCJtYW5hX3NwcmluZyI6ZmFsc2UsInJlc3RvcmF0aXZlX3RvdGVtcyI6dHJ1ZSwiYmxlc3Npbmdfb2Zfd2lzZG9tIjp0cnVlLCJpbXBfYmxlc3Npbmdfb2Zfd2lzZG9tIjpmYWxzZSwiYmxlc3Npbmdfb2Zfa2luZ3MiOnRydWUsImRydW1zX29mX2ZvcmdvdHRlbl9raW5ncyI6ZmFsc2UsImJ1ZmZfZG1nIjp0cnVlLCJidWZmX3NwZWxsX2NyaXQiOmZhbHNlLCJidWZmX2hhc3RlIjp0cnVlLCJidWZmX3NwZWxsX2hhc3RlIjp0cnVlLCJtYW5hX3JlcGxlbmlzaG1lbnQiOnRydWUsImZvY3VzX21hZ2ljIjp0cnVlLCJoZXJvaWNfcHJlc2VuY2UiOnRydWUsInByb2Zfc2tpbm5pbmciOmZhbHNlLCJwcm9mX2FsY2hlbXkiOmZhbHNlLCJwcm9mX2VuZ2luZWVyIjp0cnVlLCJmb29kIjozNDc2NywiZmxhc2siOjQ2Mzc2LCJiYXR0bGVfZWxpeGlyIjowLCJndWFyZGlhbl9lbGl4aXIiOjAsInN1bGZ1cm9uX3NsYW1tZXIiOmZhbHNlLCJibGFja19tYWdpYyI6ZmFsc2UsImxpZ2h0d2VhdmVfZW1icm9pZGVyeSI6dHJ1ZSwiZGFya2dsb3dfZW1icm9pZGVyeSI6ZmFsc2UsImh5cGVyc3BlZWRfYWNjZWxlcmF0b3JzIjp0cnVlLCJhc2hlbl9iYW5kIjpmYWxzZSwibmliZWx1bmdfaGMiOmZhbHNlLCJuaWJlbHVuZ19ubSI6ZmFsc2UsInQzXzJzZXQiOmZhbHNlLCJ0NV8yc2V0IjpmYWxzZSwidDVfNHNldCI6ZmFsc2UsInQ2XzJzZXQiOmZhbHNlLCJ0Nl80c2V0IjpmYWxzZSwidDdfMnNldCI6ZmFsc2UsInQ3XzRzZXQiOmZhbHNlLCJ0OF8yc2V0IjpmYWxzZSwidDhfNHNldCI6ZmFsc2UsInQ5XzJzZXQiOnRydWUsInQ5XzRzZXQiOnRydWUsInQxMF8yc2V0IjpmYWxzZSwidDEwXzRzZXQiOmZhbHNlLCJ1ZGNfMnNldCI6ZmFsc2UsInVkY18zc2V0IjpmYWxzZSwidWRjXzRzZXQiOmZhbHNlLCJjdWRjXzNzZXQiOmZhbHNlLCJwcmVfbWlycm9yX2ltYWdlIjp0cnVlLCJwcmVfd2F0ZXJfZWxlbWVudGFsIjpmYWxzZSwicHJlX2luY2FudGVyc19hYnNvcnB0aW9uIjpmYWxzZSwicHJlX21hbmFfaW5jYW50ZXJzX2Fic29ycHRpb24iOnRydWUsInByZV9jYXN0IjpmYWxzZSwid3Jpc3Rfc29ja2V0IjpmYWxzZSwiaGFuZHNfc29ja2V0IjpmYWxzZSwid2Fpc3Rfc29ja2V0Ijp0cnVlLCJwb3Rpb24iOjQwMjEyLCJwcmVfcG90aW9uIjowLCJjb25qdXJlZCI6MCwibWV0YV9nZW0iOjQxMjg1LCJ0cmlua2V0MSI6NDU1MTgsInRyaW5rZXQyIjo0NzE4Miwicm90YXRpb24iOjEwLCJyb3RfYWIzX21hbmEiOjE1LCJyb3RfYWJfbm9fbWJfbWFuYSI6MTAwLCJyb3RfYWJzX2FwIjowLCJyb3RfbWJfYmVsb3dfYWIiOjAsInJvdF9tYl9tYW5hIjoxMCwicm90X2ljZV9sYW5jZSI6ZmFsc2UsInJvdF9icmFpbl9mcmVlemVfZmlyZWJhbGwiOmZhbHNlLCJyb3RfYnJhaW5fZnJlZXplX2hvbGQiOjE1LCJyb3RfYmxhY2tfbWFnaWMiOmZhbHNlLCJyb3RfYmxhY2tfbWFnaWNfZW5jaCI6MCwiZXZvX3RpY2tzIjowLCJ0aW1pbmdzIjpbeyJpZCI6NiwibmFtZSI6ImFyY2FuZV9wb3dlciIsInQiOjIsIndhaXRfdCI6MCwid2FpdF9mb3JfYnVmZiI6MH0seyJpZCI6OCwibmFtZSI6ImJsb29kbHVzdCIsInQiOjIsIndhaXRfdCI6MCwid2FpdF9mb3JfYnVmZiI6MH0seyJpZCI6MTEsIm5hbWUiOiJoeXBlcnNwZWVkX2FjY2VsZXJhdG9ycyIsInQiOjIsIndhaXRfdCI6MCwid2FpdF9mb3JfYnVmZiI6MH0seyJpZCI6NywibmFtZSI6ImljeV92ZWlucyIsInQiOjIsIndhaXRfdCI6MCwid2FpdF9mb3JfYnVmZiI6MH0seyJpZCI6MTQsIm5hbWUiOiJwb3Rpb24iLCJ0IjoyLCJ3YWl0X3QiOjAsIndhaXRfZm9yX2J1ZmYiOjB9XSwiaW50ZXJydXB0aW9ucyI6W10sImJ1aWxkIjoiaHR0cHM6Ly93d3cud293aGVhZC5jb20vd290bGsvdGFsZW50LWNhbGMvbWFnZS8yMzAwMDUxMzMxMDAzMzAxNTAzMjMxMDI1MDUzMjEtMDMtMDIzMjAzMDAxXzAwMXdyMjExcTFiMjFxMXkzMXJqNDQxcmo1NTFyajciLCJzdGF0cyI6eyJpbnRlbGxlY3QiOjE3NjUsInNwaXJpdCI6NzM2LCJtcDUiOjkyLCJjcml0IjozNC42NDIyMzI2ODkyMzE5NiwiaGl0IjoxMi4wMDU0ODk0Nzg0OTk1NDMsImhhc3RlIjowLCJzcGVsbF9wb3dlciI6MjkxNywiY3JpdF9yYXRpbmciOjc4NywiaGl0X3JhdGluZyI6MjEwLCJoYXN0ZV9yYXRpbmciOjg0Nn0sImN1c3RvbV9zdGF0cyI6eyJpbnRlbGxlY3QiOjAsInNwaXJpdCI6MCwibXA1IjowLCJzcGVsbF9wb3dlciI6MCwiY3JpdF9yYXRpbmciOjAsImhpdF9yYXRpbmciOjAsImhhc3RlX3JhdGluZyI6MCwiYmFzZSI6MH0sInRhbGVudHMiOnsiYXJjYW5lX2ZvY3VzIjozLCJjbGVhcmNhc3QiOjUsIm1hZ2ljX2F0dHVuZW1lbnQiOjEsInNwZWxsX2ltcGFjdCI6Mywic3R1ZGVudF9vZl90aGVfbWluZCI6MywiZm9jdXNfbWFnaWMiOjEsImFyY2FuZV9zaGllbGRpbmciOjAsImFyY2FuZV9tZWRpdGF0aW9uIjozLCJ0b3JtZW50X29mX3RoZV93ZWFrIjozLCJwcmVzZW5jZV9vZl9taW5kIjoxLCJhcmNhbmVfbWluZCI6NSwiYXJjYW5lX2luc3RhYmlsaXR5IjozLCJhcmNhbmVfcG90ZW5jeSI6MiwiYXJjYW5lX2VtcG93ZXJtZW50IjozLCJhcmNhbmVfcG93ZXIiOjEsImluY2FudGVyc19hYnNvcnB0aW9uIjowLCJhcmNhbmVfZmxvZXMiOjIsIm1pbmRfbWFzdGVyeSI6NSwibWlzc2lsZV9iYXJyYWdlIjo1LCJuZXRoZXJ3aW5kX3ByZXNlbmNlIjozLCJzcGVsbF9wb3dlciI6MiwiYXJjYW5lX2JhcnJhZ2UiOjEsImltcF9maXJlX2JsYXN0IjowLCJpbmNpbmVyYXRpb24iOjMsImltcF9maXJlYmFsbCI6MCwiaWduaXRlIjowLCJ3b3JsZF9pbl9mbGFtZXMiOjAsInB5cm9ibGFzdCI6MCwiaW1wX3Njb3JjaCI6MCwibWFzdGVyX29mX2VsZW1lbnRzIjowLCJwbGF5aW5nX3dpdGhfZmlyZSI6MCwiY3JpdGljYWxfbWFzcyI6MCwiYmxhc3Rfd2VhdmUiOjAsImZpcmVfcG93ZXIiOjAsInB5cm9tYW5pYWMiOjAsImNvbWJ1c3Rpb24iOjAsIm1vbHRlbl9mdXJ5IjowLCJlbXBvd2VyZWRfZmlyZSI6MCwiZmlyZXN0YXJ0ZXIiOjAsImRyYWdvbnNfYnJlYXRoIjowLCJob3Rfc3RyZWFrIjowLCJidXJub3V0IjowLCJsaXZpbmdfYm9tYiI6MCwiaW1wX2Zyb3N0Ym9sdCI6MiwiaWNlX2Zsb2VzIjozLCJpY2Vfc2hhcmRzIjoyLCJwcmVjaXNpb24iOjMsInBpZXJjaW5nX2ljZSI6MCwiaWN5X3ZlaW5zIjoxLCJmcm9zdF9jaGFubmVsaW5nIjowLCJzaGF0dGVyIjowLCJjb2xkX3NuYXAiOjAsImltcF9jb25lX29mX2NvbGQiOjAsImNvbGRfYXNfaWNlIjowLCJ3aW50ZXJzX2NoaWxsIjowLCJhcmN0aWNfd2luZHMiOjAsImVtcG93ZXJlZF9mcm9zdGJvbHQiOjAsImZpbmdlcnNfb2ZfZnJvc3QiOjAsImJyYWluX2ZyZWV6ZSI6MCwid2F0ZXJfZWxlbWVudGFsIjowLCJlbmR1cmluZ193aW50ZXIiOjAsImNoaWxsZWRfdG9fdGhlX2JvbmUiOjAsImRlZXBfZnJlZXplIjowfSwiZ2x5cGhzIjp7ImFyY2FuZV9iYXJyYWdlIjpmYWxzZSwiYXJjYW5lX2JsYXN0Ijp0cnVlLCJhcmNhbmVfZXhwbG9zaW9uIjpmYWxzZSwiYXJjYW5lX21pc3NpbGVzIjp0cnVlLCJhcmNhbmVfcG93ZXIiOmZhbHNlLCJldGVybmFsX3dhdGVyIjpmYWxzZSwiZmlyZWJhbGwiOmZhbHNlLCJmcm9zdGJvbHQiOmZhbHNlLCJmcm9zdGZpcmUiOmZhbHNlLCJpY2VfbGFuY2UiOmZhbHNlLCJsaXZpbmdfYm9tYiI6ZmFsc2UsIm1hZ2VfYXJtb3IiOmZhbHNlLCJtYW5hX2dlbSI6ZmFsc2UsIm1pcnJvcl9pbWFnZSI6ZmFsc2UsIm1vbHRlbl9hcm1vciI6dHJ1ZSwic2NvcmNoIjpmYWxzZSwid2F0ZXJfZWxlbWVudGFsIjpmYWxzZSwiYmxhc3Rfd2F2ZSI6ZmFsc2V9LCJ0b29sdGlwcyI6ZmFsc2V9fQ==

**Comment by Cheesehyvel** [comment]
That's not how stat weights work. They are not static.
If you change the "Stat weight increment" option to 100 you will get the same number.

**Comment by jdelvare** [comment]
Thanks for your reply. I'm well aware of the fact that the Stat weight increment value doesn't change the results beyond their accuracy, and this is not what I reported.

My report is about the weights expressed as "DPS" being incorrect. In my case, when it says 1 Spell power is worth 3.93 DPS, this does not match the simulator results, where increasing the Spell power by 1 brings a gain of only 1.97 DPS. (I added 100 instead of 1, then divided the gain by 100, simply to avoid potential noise and rounding issues.)

Please verify the computations, I'm reasonably certain there's a factor 2 missing (or in excess) somewhere.

**Comment by Cheesehyvel** [comment]
It does match.
Using your profile, adding +20 (which is what you are using as stat weight increment) spell power yields 39.3 dps, and adding +100 spell powers yields 197 dps.
Stat weights are not static.

**Comment by jdelvare** [comment]
OK, I stand corrected. My previous comment was wrong and now I understand what you mean with "stat weights are not static". The Stat weight increment value **does** have an impact on the displayed numbers in "DPS mode", which I did not expect.

Now I under what the code is doing, but I still find it confusing. You compute the base DPS, then add the Stat weight increment value and compute the new DPS, compute the difference, **divide the result by 10** and display that. Why do you arbitrarily divide by 10?

I could understand that you divide the raw difference by the Stat weight increment value, to normalize the result to 1 point of stat. Or, I could understand that you don't divide the result, so that it directly reflects the DPS change for the specified increment. But dividing by some undocumented constant... That's just confusing. Is this because the Stat weight increment value used to be hard-coded to 10, before being changed to a user-changeable setting?
