### ISSUE TITLE
Missing item: Cloth Shoulders

### ISSUE THREAD

**Issue by yurpcraft** [Cheesehyvel/magesim-wotlk#4]
Please include the item name in the title and a link to the item on any wotlk database (like wotlkdb.com or wowhead).

  Mantle of Inconsolable Fear: https://www.wowhead.com/wotlk/item=47226/mantle-of-inconsolable-fear
  Iceshear Mantle: https://www.wowhead.com/wotlk/item=46344/iceshear-mantle
  Khadgar's sets (same as Sunstriders but for Ally)
  Stiffened Corpse Shoulderpads: https://www.wowhead.com/wotlk/item=50449/stiffened-corpse-shoulderpads
  Frayed Abomination Stitching Shoulders: https://www.wowhead.com/wotlk/item=49834/frayed-abomination-stitching-shoulders
  Mantle of Tattered Feathers: https://www.wowhead.com/wotlk/item=49854/mantle-of-tattered-feathers
  Very Fashionable Shoulders: https://www.wowhead.com/wotlk/item=50193/very-fashionable-shoulders
  Pauldrons/Mantle of Revered Mortality (ally/horde): https://www.wowhead.com/wotlk/item=47715/pauldrons-of-revered-mortality
  Mantle/Pauldrons of Catastrophic Emanation (ally/horde): https://www.wowhead.com/wotlk/item=47713/mantle-of-catastrophic-emanation
  Titan-Forged Shoulderpads of Salvation: https://www.wowhead.com/wotlk/item=51572/titan-forged-shoulderpads-of-salvation

**Comment by Cheesehyvel** [comment]
8aa7ec1
