### ISSUE TITLE
Missing item: Cloth Chests

### ISSUE THREAD

**Issue by yurpcraft** [Cheesehyvel/magesim-wotlk#5]
Please include the item name in the title and a link to the item on any wotlk database (like wotlkdb.com or wowhead).

  Glacial Robe: https://www.wowhead.com/wotlk/item=43583/glacial-robe
  Embrace of Madness: https://www.wowhead.com/wotlk/item=47527/embrace-of-madness
  Palebone Robes: https://www.wowhead.com/wotlk/item=49825/palebone-robes
  Khadgar's items (they're Sunfury items, for Alliance)
  Mord'rethar Robes: https://www.wowhead.com/wotlk/item=50213/mordrethar-robes
  Earth Bride's Gown: https://www.wowhead.com/wotlk/item=53498/earth-brides-gown
  Ancient Polar Bear Hide: https://www.wowhead.com/wotlk/item=50266/ancient-polar-bear-hide
  Robes of the Sleepless (Vestments of the Sleepless for Horde)
  Merlin's Robe: https://www.wowhead.com/wotlk/item=47603/merlins-robe
  Royal Moonshroud Robe: https://www.wowhead.com/wotlk/item=47606/royal-moonshroud-robe
  Flowing Robes/Vestments of Ascent: https://www.wowhead.com/wotlk/item=47264/flowing-robes-of-ascent
  Ermine Coronation Robes: https://www.wowhead.com/wotlk/item=50975/ermine-coronation-robes
  Meteor Chaser's Raiment: https://www.wowhead.com/wotlk/item=50974/meteor-chasers-raiment

**Comment by Cheesehyvel** [comment]
Will ignore Earth Bride's Gown - It was added in cata prepatch.
8aa7ec1
