### ISSUE TITLE
Missing item: Chests

### ISSUE THREAD

**Issue by yurpcraft** [Cheesehyvel/magesim-wotlk#8]
Please include:
* The item name in the title
* Link to the item on any wotlk database (like wotlkdb.com or wowhead).
* Where it drops and/or which phase it becomes available

Khadgar's Robe of Triumph (258) - Alliance T9 / Phase 3 - https://www.wowhead.com/wotlk/item=47759/khadgars-robe-of-triumph
Flowing Robes of Ascent (258) - Phase 3 / TOGC - https://www.wowhead.com/wotlk/item=47425/flowing-robes-of-ascent
Skyweaver Vestments (258) - Horde TOGC drop - https://www.wowhead.com/wotlk/item=47462/skyweaver-vestments
Bloodmage Robe (251) - First rank of T10 / Phase 4 - https://www.wowhead.com/wotlk/item=50278/bloodmage-robe
Merlin's Robe (245) - Tailoring Phase 3 Pattern - https://www.wowhead.com/wotlk/item=47604/merlins-robe (47603 is the ally equivalent, not sure if this messes up import/export otherwise you can ignore this one)
Flowing Vestments of Ascent (245) - currently duplicated in chests
Skyweaver Vestments (245) - Horde TOGC Drop - https://www.wowhead.com/wotlk/item=47301/skyweaver-vestments
Khadgar's Robe of Triumph (245) - Alliance T9 / Phase 3 - https://www.wowhead.com/wotlk/item=47756/khadgars-robe-of-triumph
Khadgar's Robe of Triumph (232) - Alliance T9 / Phase 3 - https://www.wowhead.com/wotlk/item=47749/khadgars-robe-of-conquest
Titan-Forged Raiment of Salvation - WG Phase 2 drop - https://www.wowhead.com/wotlk/item=46066/titan-forged-raiment-of-salvation
Titan-Forged Raiment of Dominance - WG Phase 2 drop - https://www.wowhead.com/wotlk/item=46065/titan-forged-raiment-of-dominance

**Comment by Cheesehyvel** [comment]
> Flowing Vestments of Ascent (245) - currently duplicated in chests
There are two different item levels, so not sure what you mean.
